"use client";
import { useEffect, useState, useRef, type FormEvent } from "react";
import { ArrowUpRight, ArrowDown, ArrowRight, ArrowLeft, Minus, Plus, Check, Menu, Pause, Play, LockKeyhole } from "lucide-react";
import { RadioGroup,RadioGroupItem } from "@/components/ui/radio-group";
import { Dialog,DialogContent,DialogTitle,DialogDescription } from "@/components/ui/dialog";
import { Sheet,SheetContent,SheetTitle,SheetDescription } from "@/components/ui/sheet";
import { products,sizes,getProduct,currency,calculateCart,type Product,type CartLine,type Size } from "@/lib/commerce/catalog";
import { validateCheckout } from "@/lib/commerce/validation";
import HeroObject from "./hero-object";

type CheckoutStep="details"|"payment"|"success";
type Customer={name:string;email:string;phone:string;address:string;city:string;postalCode:string};
const emptyCustomer:Customer={name:"",email:"",phone:"",address:"",city:"",postalCode:""};
const links=[["WORLD","world"],["MANIFESTO","manifesto"],["SILHOUETTES","silhouettes"],["CONTACT","contact"]];
export function GarmentImage({index,className="",alt}:{index:number;className?:string;alt?:string}){return <div className={`garment-image ${className}`}><img src="/assets/garment-studies.webp" alt={alt??["Washed black oversized T-shirt concept, front view","Black boxy zip jacket concept, front view","Long black hooded coat concept, front view"][index]} style={{left:`-${index*100}%`}} width="2172" height="724" loading="lazy" decoding="async" /></div>;}
function Eyebrow({children}:{children:React.ReactNode}){return <p className="eyebrow">{children}</p>;}

export default function BrandExperience({offline=false}:{offline?:boolean}){
  const [menuOpen,setMenuOpen]=useState(false);
  const returnFocus=useRef<HTMLElement|null>(null);
  const [bagOpen,setBagOpen]=useState(false);
  const [selected,setSelected]=useState<Product|null>(null);
  const [size,setSize]=useState<Size>("M");
  const [cart,setCart]=useState<CartLine[]>([]);
  const [cartReady,setCartReady]=useState(false);
  const [paused,setPaused]=useState(false);
  const [contactInfo,setContactInfo]=useState<string|null>(null);
  const [signalEmail,setSignalEmail]=useState("");
  const [signalFeedback,setSignalFeedback]=useState("");
  const [checkoutOpen,setCheckoutOpen]=useState(false);
  const [checkoutStep,setCheckoutStep]=useState<CheckoutStep>("details");
  const [customer,setCustomer]=useState<Customer>(emptyCustomer);
  const [method,setMethod]=useState("QRIS / e-wallet");
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState("");
  const [order,setOrder]=useState<{id:string;total:number;mode:string;redirectUrl?:string}|null>(null);
  const [announcement,setAnnouncement]=useState("");
  const totals=calculateCart(cart);
  const count=cart.reduce((sum,line)=>sum+line.quantity,0);
  useEffect(()=>{
    try{const saved=JSON.parse(localStorage.getItem("cartier-bag-v1")??"[]");if(Array.isArray(saved))setCart(saved.filter((line:CartLine)=>getProduct(line.id)&&sizes.includes(line.size)&&Number.isInteger(line.quantity)&&line.quantity>0&&line.quantity<=5).slice(0,12));}catch{/* A blocked browser store must never block the shop. */}
    setCartReady(true);
    const media=window.matchMedia("(prefers-reduced-motion: reduce)");
    const change=()=>setPaused(media.matches);change();media.addEventListener("change",change);return()=>media.removeEventListener("change",change);
  },[]);
  useEffect(()=>{if(cartReady)try{localStorage.setItem("cartier-bag-v1",JSON.stringify(cart));}catch{}},[cart,cartReady]);
  function chooseProduct(product:Product){returnFocus.current=document.activeElement as HTMLElement;setSize("M");setSelected(product);}
  function addToBag(){
    if(!selected)return;
    const existing=cart.find(line=>line.id===selected.id&&line.size===size);
    if(existing&&existing.quantity>=5){setAnnouncement("Maximum five per size in this preview.");return;}
    setCart(previous=>existing?previous.map(line=>line.id===selected.id&&line.size===size?{...line,quantity:line.quantity+1}:line):[...previous,{id:selected.id,size,quantity:1}]);
    setAnnouncement(`${selected.name}, size ${size}, added to your bag.`);setSelected(null);setBagOpen(true);
  }
  function quantity(id:string,lineSize:Size,change:number){setCart(previous=>previous.map(line=>line.id===id&&line.size===lineSize?{...line,quantity:Math.min(5,line.quantity+change)}:line).filter(line=>line.quantity>0));}
  function beginCheckout(){setBagOpen(false);setCheckoutOpen(true);setCheckoutStep("details");setError("");setOrder(null);}
  async function prepareOrder(event:FormEvent<HTMLFormElement>){
    event.preventDefault();setError("");setBusy(true);
    try{
      if(!cart.length)throw new Error("Your bag is empty. Add a piece to continue.");
      // The downloadable preview and hosted app share the same checkout rules.
      // The server repeats these checks; browser validation is not a trust boundary.
      const checkout=validateCheckout({items:cart,customer});
      if(offline){setOrder({id:`DEMO-${Date.now().toString(36).toUpperCase()}`,total:checkout.total,mode:"demo"});setCheckoutStep("payment");return;}
      const response=await fetch("/api/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:checkout.items,customer:checkout.customer})});
      const result=await response.json() as {id:string;total:number;mode:string;redirectUrl?:string;error?:string};if(!response.ok)throw new Error(result.error??"Checkout is unavailable. Please try again.");
      setOrder(result);setCheckoutStep("payment");
    }catch(err){setError(err instanceof Error?err.message:"We could not prepare checkout. Try again.");}finally{setBusy(false);}
  }
  function completeDemo(){setBusy(true);window.setTimeout(()=>{setBusy(false);setCheckoutStep("success");setCart([]);setCustomer(emptyCustomer);},650);}
  function joinSignal(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(signalEmail.trim())){setSignalFeedback("Enter a valid email address.");return;}setSignalFeedback("Signal received — preview only. Your email has not been saved or subscribed.");setSignalEmail("");}
  return <div className={`page-shell ${paused?"pause-motion":""}`}>
    <a className="skip-link" href="#main">Skip to content</a>
    <div className="loading-mark" aria-hidden="true"><img src="/assets/wordmark.svg" alt="" width="170" height="40"/><div className="loading-line"/></div>
    <div className="grain" aria-hidden="true"/>
    <p className="sr-only" aria-live="polite">{announcement}</p>
    <header className="site-nav">
      <a className="nav-brand" href="#home" aria-label="CARTIER home"><img src="/assets/wordmark.svg" alt="CARTIER" width="108" height="30"/></a>
      <nav className="desktop-nav" aria-label="Main navigation">{links.map(([label,id])=><a key={id} href={`#${id}`}>{label}</a>)}<a href="#release">FIRST RELEASE</a></nav>
      <div className="nav-actions"><button id="bag-toggle" className="bag-toggle" onClick={()=>setBagOpen(true)} aria-label={`Open bag, ${count} items`}>BAG <span className="bag-count">{count}</span></button><button id="menu-toggle" className="menu-toggle" aria-label="Open navigation" aria-expanded={menuOpen} onClick={()=>setMenuOpen(true)}><Menu size={21}/></button></div>
    </header>
    <main id="main">
      <section className="hero" id="home" aria-labelledby="hero-title">
        <div className="hero-topline mono"><span>INDEPENDENT CLOTHING LABEL</span><span>EST. 2026 / CHAPTER 001</span></div>
        <img className="hero-wordmark" src="/assets/wordmark.svg" alt="CARTIER" width="682" height="160" fetchPriority="high"/>
        <HeroObject paused={paused}/>
        <div className="hero-copy"><h1 id="hero-title">BORN AFTER<br/>MIDNIGHT.</h1><p>Independent garments shaped by noise, pressure, and the hours nobody sees.</p></div>
        <div className="hero-index mono"><img className="sigil-mini" src="/assets/emblem.svg" alt="" width="34" height="34"/><span>NO FIXED FORM.</span><span>NO BORROWED IDENTITY.</span></div>
        <div className="hero-bottom mono"><a className="scroll-cue" href="#world"><ArrowDown size={17}/> ENTER THE WORLD</a><span className="edition">[ THE FIRST IMPRESSION ]</span><button className="motion-button" onClick={()=>setPaused(!paused)} aria-pressed={paused}>{paused?<Play size={13}/>:<Pause size={13}/>} MOTION {paused?"OFF":"ON"}</button></div>
      </section>
      <section className="world section-wrap" id="world" aria-labelledby="world-title">
        <div className="section-heading"><div><Eyebrow>01 / THE WORLD</Eyebrow><h2 id="world-title">OUTSIDE THE FRAME.</h2></div><span className="mono muted">AFTER DARK.<br/>BEFORE ANYONE.</span></div>
        <div className="world-grid"><figure className="reveal"><div className="world-image"><img src="/assets/world.webp" width="1254" height="1254" alt="Two fictional models in oversized black garments under harsh flash against a concrete backstage wall" loading="lazy" decoding="async"/><span className="image-corner mono">C — 001</span></div><figcaption className="world-caption mono"><span>STUDIES IN THE UNSEEN</span><span>CAMPAIGN CONCEPT / 2026</span></figcaption></figure><div className="world-copy reveal"><h3>THE CITY GOES QUIET.<br/><span>WE DON’T.</span></h3><p>Concrete underfoot. Feedback in the walls. A shape caught in the flash, gone before it settles.</p><p>CARTIER starts where the familiar ends. Garments with weight, room, and a point of view.</p><div className="world-stamp"><img src="/assets/emblem.svg" alt="" width="53" height="62"/><p>INDEPENDENT BY DESIGN.<br/>DEFINED BY WHAT WE MAKE.</p></div><a className="text-link" href="#manifesto">READ THE MANIFESTO <ArrowUpRight size={17}/></a></div></div>
      </section>
      <section className="manifesto" id="manifesto" aria-labelledby="manifesto-title"><div className="manifesto-top"><Eyebrow>02 / THE MANIFESTO</Eyebrow><span className="mono">A NOTE FROM THE INSIDE</span></div><h2 className="manifesto-label reveal" id="manifesto-title">PRESSURE MAKES<br/><span>something</span> REAL.</h2><div className="manifesto-body reveal"><p>We work in the hours left unclaimed. Away from the noise of approval, close to the noise that moves us. Clothing is how we take up space: a shape, a weight, a refusal to disappear.</p><p>Nothing arrives untouched. Pressure leaves a mark. We cut around it, build through it, let it become form. We make only what we mean, in small runs, at our own pace. No borrowed identity. No permission to begin. The night is still ours.</p></div><div className="manifesto-footer"><img src="/assets/wordmark.svg" alt="CARTIER" width="100" height="24"/><p className="mono">WRITTEN AFTER MIDNIGHT.<br/>MADE TO STAY.</p></div></section>
      <section className="silhouettes section-wrap" id="silhouettes" aria-labelledby="silhouettes-title"><div className="section-heading"><div><Eyebrow>03 / FORM STUDIES</Eyebrow><h2 id="silhouettes-title">SHAPE BEFORE NOISE.</h2></div><span className="mono muted">THREE FORMS.<br/>ONE INSTINCT.</span></div><div className="study-grid">{products.map(product=><article className="study-panel reveal" key={product.id}><div><GarmentImage index={product.image}/><span className="study-index mono">FIG. {product.number}</span></div><div className="study-bottom"><h3>{product.category}</h3><p>{product.attitude}</p><button className="text-link" onClick={()=>chooseProduct(product)}>EXPLORE THE STUDY <ArrowUpRight size={17}/></button></div></article>)}</div><p className="study-note mono">PROPORTION / VOLUME / WEIGHT — CONCEPT GARMENTS. FINAL DESIGNS ARE STILL TAKING SHAPE.</p></section>
      <section className="campaign" aria-labelledby="campaign-title"><img src="/assets/campaign.webp" alt="A blurred figure wearing long black outerwear crossing an industrial loading dock at night" width="1672" height="941" loading="lazy" decoding="async"/><h2 className="reveal" id="campaign-title">NO PERMISSION<br/>REQUIRED.</h2><div className="mono"><span>CARTIER / AFTER HOURS</span><small>NOT EVERY MOVEMENT<br/>NEEDS AN AUDIENCE.</small></div></section>
      <section className="release section-wrap" id="release" aria-labelledby="release-title"><div className="section-heading release-heading"><div><Eyebrow>04 / FIRST RELEASE — PREVIEW</Eyebrow><h2 id="release-title">THE FIRST FORM.</h2></div><p>Three studies from the first chapter.<br/>Explore the pieces and try the demo checkout. No orders or payments are taken.</p></div><div className="release-grid">{products.map(product=><article className="release-item" key={product.id}><GarmentImage index={product.image}/><div><div className="product-meta"><h3>{product.name}</h3><p>{currency(product.price)}</p></div><p className="product-line">Washed black / Concept {product.number}</p><button className="outline-button full-width" onClick={()=>chooseProduct(product)}>VIEW PIECE <Plus size={16}/></button></div></article>)}</div><p className="study-note mono">ALL PRICES, MATERIALS AND DELIVERY COSTS ARE DEMONSTRATION VALUES. FIRST RELEASE DATE TO BE ANNOUNCED.</p></section>
      <section className="signal" id="contact" aria-labelledby="signal-title"><Eyebrow>05 / STAY WITHIN REACH</Eyebrow><h2 className="reveal" id="signal-title">FIRST SIGNAL<br/>COMING SOON.</h2><p>Release notes. Rare updates. Nothing extra.</p><form className="signal-form" onSubmit={joinSignal}><label className="sr-only" htmlFor="signal-email">Email address</label><input id="signal-email" type="email" autoComplete="email" placeholder="Your email address" value={signalEmail} onChange={event=>{setSignalEmail(event.target.value);setSignalFeedback("");}} required maxLength={254}/><button type="submit">JOIN THE LIST <ArrowUpRight size={19}/></button></form><p className="signal-privacy muted">Your inbox stays yours. This preview does not store your email.</p><p className="signal-feedback" aria-live="polite">{signalFeedback}</p></section>
    </main>
    <footer className="footer"><div className="footer-top"><img src="/assets/wordmark.svg" alt="CARTIER" width="185" height="50"/><div className="footer-links"><button className="placeholder-link" onClick={()=>setContactInfo("Instagram")}>INSTAGRAM — COMING SOON <ArrowUpRight size={14}/></button><button className="placeholder-link" onClick={()=>setContactInfo("Email")}>EMAIL — COMING SOON <ArrowUpRight size={14}/></button></div></div><div className="footer-bottom mono"><span>© {new Date().getFullYear()} CARTIER</span><span>INDEPENDENT CLOTHING LABEL</span><span>PROTOTYPE IDENTITY / DEMO STORE</span></div></footer>
    <Sheet open={menuOpen} onOpenChange={setMenuOpen}><SheetContent className="menu-sheet" onCloseAutoFocus={event=>{event.preventDefault();document.getElementById("menu-toggle")?.focus({preventScroll:true});}}><SheetTitle className="mono">CARTIER / INDEX</SheetTitle><SheetDescription>Enter the world. Find your form.</SheetDescription><nav aria-label="Mobile navigation">{[...links,["FIRST RELEASE","release"]].map(([label,id])=><a key={id} href={`#${id}`} onClick={()=>setMenuOpen(false)}>{label}</a>)}</nav><p className="mono muted mt-auto">INDEPENDENT CLOTHING LABEL / 2026</p></SheetContent></Sheet>
    <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent className="commerce-dialog" onCloseAutoFocus={event=>{event.preventDefault();if(!bagOpen)returnFocus.current?.focus({preventScroll:true});}}>{selected&&<div className="product-dialog-grid"><GarmentImage index={selected.image}/><div className="product-detail"><Eyebrow>CONCEPT {selected.number} / DEMO PIECE</Eyebrow><DialogTitle>{selected.name}</DialogTitle><DialogDescription>{selected.description}</DialogDescription><p className="price">{currency(selected.price)} <span className="muted">/ demo price</span></p><div><p className="size-label" id="size-label">Select size</p><RadioGroup className="size-options" value={size} onValueChange={value=>setSize(value as Size)} aria-labelledby="size-label">{sizes.map(value=><label className="size-choice" key={value}><RadioGroupItem className="size-radio" value={value} aria-label={value}/><span>{value}</span></label>)}</RadioGroup></div><button className="solid-button full-width" onClick={addToBag} disabled={cart.some(line=>line.id===selected.id&&line.size===size&&line.quantity>=5)}>ADD TO BAG <Plus size={17}/></button><p className="product-specs">{selected.fabric}<br/>{selected.fit}<br/>Color: washed black</p><p className="prototype-note">A design study, not a released product. Measurements and final materials will be announced with the release.</p></div></div>}</DialogContent></Dialog>
    <Sheet open={bagOpen} onOpenChange={setBagOpen}><SheetContent className="cart-sheet" onCloseAutoFocus={event=>{event.preventDefault();if(!checkoutOpen)document.getElementById("bag-toggle")?.focus({preventScroll:true});}}><SheetTitle>YOUR BAG / {count}</SheetTitle><SheetDescription>Demo pieces. No real orders or charges.</SheetDescription>{!cart.length?<div className="empty-bag"><h3>NOTHING HERE. YET.</h3><p className="muted">Start with a form that feels like you.</p><a className="text-link" href="#release" onClick={()=>setBagOpen(false)}>EXPLORE THE FIRST FORM <ArrowRight size={17}/></a></div>:<><div className="cart-lines">{cart.map(line=>{const product=getProduct(line.id)!;return <article className="cart-line" key={`${line.id}-${line.size}`}><GarmentImage index={product.image}/><div><h3>{product.name}</h3><p>SIZE {line.size} / WASHED BLACK</p><p>{currency(product.price*line.quantity)}</p><div className="quantity"><button onClick={()=>quantity(line.id,line.size,-1)} aria-label={`Decrease ${product.name} size ${line.size} quantity`}><Minus size={13}/></button><span aria-label={`Quantity ${line.quantity}`}>{line.quantity}</span><button disabled={line.quantity>=5} onClick={()=>quantity(line.id,line.size,1)} aria-label={`Increase ${product.name} size ${line.size} quantity`}><Plus size={13}/></button><button className="remove" onClick={()=>setCart(previous=>previous.filter(item=>!(item.id===line.id&&item.size===line.size)))} aria-label={`Remove ${product.name} size ${line.size}`}>Remove</button></div></div></article>;})}</div><div className="cart-summary"><div className="total-row"><span>Subtotal</span><span>{currency(totals.subtotal)}</span></div><p className="prototype-note">Demo delivery: {currency(totals.shipping)}. No additional demo taxes.</p><button className="solid-button full-width" onClick={beginCheckout}>CHECKOUT <ArrowRight size={17}/></button><p className="prototype-note">Prices and delivery are placeholders for this preview.</p></div></>}</SheetContent></Sheet>
    <Dialog open={checkoutOpen} onOpenChange={open=>{if(!busy)setCheckoutOpen(open);}}><DialogContent className="commerce-dialog" onCloseAutoFocus={event=>{event.preventDefault();document.getElementById("bag-toggle")?.focus({preventScroll:true});}} onEscapeKeyDown={event=>{if(busy)event.preventDefault();}} onInteractOutside={event=>{if(busy)event.preventDefault();}}>
      {checkoutStep==="details"&&<div className="checkout-content"><div className="checkout-top"><div><DialogTitle>CHECKOUT</DialogTitle><DialogDescription>Your first form. Your own pace.</DialogDescription></div><span className="demo-tag">DEMO / NO CHARGE</span></div><div className="checkout-grid"><form className="checkout-form" onSubmit={prepareOrder}><p className="prototype-note">Use sample details to explore this preview. Nothing will be shipped.</p>{([['name','Full name','text','name'],['email','Email address','email','email'],['phone','Phone number','tel','tel'],['address','Street address','text','street-address']] as const).map(([key,label,type,autoComplete])=><label className="form-field" key={key}>{label}<input name={key} type={type} autoComplete={autoComplete} value={customer[key]} required minLength={key==="phone"?8:key==="address"?5:key==="name"?2:3} maxLength={key==="email"?254:key==="address"?200:key==="phone"?20:80} onChange={event=>setCustomer({...customer,[key]:event.target.value})}/></label>)}<div className="two-fields"><label className="form-field">City<input name="city" autoComplete="address-level2" value={customer.city} required minLength={2} maxLength={80} onChange={event=>setCustomer({...customer,city:event.target.value})}/></label><label className="form-field">Postal code<input name="postalCode" autoComplete="postal-code" inputMode="numeric" pattern="[0-9]{5}" maxLength={5} placeholder="5 digits" value={customer.postalCode} required onChange={event=>setCustomer({...customer,postalCode:event.target.value})}/></label></div><p className="prototype-note">Indonesia / standard delivery (demo). Your details are cleared after the demo completes.</p>{error&&<p className="form-error" role="alert">{error}</p>}<button className="solid-button full-width" type="submit" disabled={busy}>{busy?"PREPARING…":"CONTINUE TO PAYMENT"}<ArrowRight size={17}/></button></form><aside className="order-summary"><h3>ORDER SUMMARY</h3>{cart.map(line=><div className="summary-line" key={`${line.id}-${line.size}`}><span>{getProduct(line.id)!.name}<small>Size {line.size} × {line.quantity}</small></span><span>{currency(getProduct(line.id)!.price*line.quantity)}</span></div>)}<hr/><div className="total-row"><span>Subtotal</span><span>{currency(totals.subtotal)}</span></div><div className="total-row"><span>Delivery</span><span>{currency(totals.shipping)}</span></div><hr/><div className="total-row"><strong>Total</strong><strong>{currency(totals.total)}</strong></div><p className="prototype-note">Demonstration values. No additional demo taxes. Final shipping and tax rules will be confirmed before launch.</p></aside></div></div>}
      {checkoutStep==="payment"&&order&&<div className="payment-step"><span className="demo-tag">{order.mode==="sandbox"?"MIDTRANS SANDBOX":"DEMO PAYMENT"} / NO REAL CHARGE</span><DialogTitle className="mt-6">ONE LAST STEP.</DialogTitle><DialogDescription>{order.mode==="sandbox"?"Continue to the provider’s sandbox to test payment. Use sandbox payment details only.":"Choose a payment method to preview the experience. No payment details are collected."}</DialogDescription><h3>{currency(order.total)}</h3><p className="mono muted">REFERENCE / {order.id}</p>{order.mode==="demo"&&<RadioGroup className="payment-options" value={method} onValueChange={setMethod} aria-label="Demo payment method">{["QRIS / e-wallet","Bank transfer","Credit / debit card"].map(option=><label className="payment-option" key={option}><RadioGroupItem value={option} aria-label={option}/><span>{option}</span></label>)}</RadioGroup>}<p className="prototype-note my-5"><LockKeyhole size={13} className="inline mr-2"/>{order.mode==="demo"?"Simulation only. Do not enter card, bank, or wallet details.":"Sandbox payment is hosted by Midtrans. This website never collects card details."}</p>{order.mode==="demo"?<button className="solid-button full-width" onClick={completeDemo} disabled={busy}>{busy?"COMPLETING DEMO…":"COMPLETE DEMO ORDER"}<ArrowRight size={17}/></button>:<a className="solid-button full-width" href={order.redirectUrl}>OPEN SANDBOX PAYMENT <ArrowUpRight size={17}/></a>}<button className="checkout-back" onClick={()=>setCheckoutStep("details")} disabled={busy}><ArrowLeft size={14}/> Back to details</button></div>}
      {checkoutStep==="success"&&<div className="success-panel"><Check size={45} strokeWidth={1}/><DialogTitle asChild><h2>DEMO COMPLETE.</h2></DialogTitle><DialogDescription>No payment was taken. No order was placed.</DialogDescription><p>You’ve reached the end of the checkout preview. The first real release is still to come.</p><p className="mono">{order?.id}<br/>{method} / SIMULATED</p><button className="solid-button full-width" onClick={()=>setCheckoutOpen(false)}>BACK TO THE WORLD <ArrowUpRight size={17}/></button></div>}
    </DialogContent></Dialog>
    <Dialog open={!!contactInfo} onOpenChange={open=>{if(!open)setContactInfo(null);}}><DialogContent className="commerce-dialog contact-dialog"><DialogTitle>{contactInfo?.toUpperCase()} / COMING SOON</DialogTitle><DialogDescription>The official {contactInfo==="Instagram"?"Instagram handle":"contact address"} will be added before launch. There is no connected account in this preview.</DialogDescription><a className="text-link" href="#contact" onClick={()=>setContactInfo(null)}>STAY WITHIN REACH <ArrowUpRight size={17}/></a></DialogContent></Dialog>
  </div>;
}
